### PR TITLE
Fix: added reset and restored events

### LINKED ISSUE #8: Missing reset and restored events
Each `ScoringSet` should trigger events to indicate when they have been reset and restored. The `scoring:set:reset` event is used in https://github.com/adaptlearning/adapt-contrib-scoringResults.

### PR DESCRIPTION
**Pull request by danielghost**
Fixes #8.

### Fix
* Added missing reset and restored events for each `ScoringSet`

### CODE REVIEW

File: js/adapt-contrib-scoring.js [hunk 1]
```diff
@@ -34,8 +34,8 @@ export {
 class Scoring extends Backbone.Controller {
 
   initialize() {
-    this._rawSets = [];
     this.listenTo(Data, {
+      'loading': this.onDataLoading,
```
Comment (cahirodoherty-learningpool) [inline js/adapt-contrib-scoring.js:38]: Minor: Quotes can be removed
```suggestion
      loading: this.onDataLoading,
```

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀
