### PR TITLE
Fix: prevent sets created from query intersections from triggering events and running unsuitable methods

### LINKED ISSUE #15: Subsets created from query intersections trigger restored events
Subsets created from [query intersections ](https://github.com/adaptlearning/adapt-contrib-scoring/blob/3a4b504fc7fe75039a2ed909c72edfa866f7ff1a/js/utils.js#L68C17-L68C41) trigger _restored_ events, which should be excluded as per _register_ events.

### PR DESCRIPTION
**Pull request by danielghost**
Fixes #15.

### Fix
* Prevent sets created from query intersections from triggering events and running unsuitable methods.

### CODE REVIEW

File: js/ScoringSet.js [hunk 1]
```diff
@@ -45,8 +45,7 @@ export default class ScoringSet extends Backbone.Controller {
     this._title = title;
     this._isScoreIncluded = _isScoreIncluded;
     this._isCompletionRequired = _isCompletionRequired;
-    // only register root sets as subsets are dynamically created when required
-    if (!this.subsetParent) this.register();
+    this.register();
```
Comment (oliverfoster) [inline js/ScoringSet.js:48]: intersected sets should not be registering themselves.
